# Generated by Django 6.0.6 on 2026-07-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything_important', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_publish_bb7600_idx',
            old_name='everything__publish_f5a69f_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_post',
        ),
    ]
