# Generated by Django 6.0.6 on 2026-07-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything_important', '0003_rename_everything__publish_f5a69f_idx_blog_post_publish_bb7600_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
